services:
  - type: web
    name: restaurant-api
    env: node
    region: singapore
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: PORT
        value: 3001
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false

